{% set name = "numcodecs" %}
{% set version = "0.16.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0d0fb60852f84c0bd9543cc4d2ab9eefd37fc8efcc410acd4777e62a1d300318

build:
  number: 1
  skip: true  # [py<311]
  script_env:
    - DISABLE_NUMCODECS_AVX2=""
    - DISABLE_NUMCODECS_SSE2=""  # [not x86]
  script:
    - export CFLAGS="${CFLAGS} -pthread"  # [aarch64 or ppc64le]
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - numpy                                  # [build_platform != target_platform]
  host:
    - python
    - pip
    - cython
    - setuptools >=64
    - setuptools_scm >=6.2
    - tomli
    - py-cpuinfo
    - numpy
  run:
    - typing_extensions
    - deprecated
    - python
    - numpy >=1.24
    # Optional dependecy included for ease of use
    - msgpack-python

test:
  requires:
    - coverage
    - flake8
    - importlib_metadata
    - pip
    - pytest
    - pytest-cov
    - pyzstd
  imports:
    - numcodecs
    - numcodecs.blosc
    - numcodecs.lz4
    - numcodecs.zstd
  commands:
    - pip check
    - pytest -v --pyargs numcodecs

about:
  home: https://github.com/zarr-developers/numcodecs
  license: MIT
  license_file: LICENSE.txt
  summary: A Python package providing buffer compression and transformation codecs for use in data storage and communication applications.

extra:
  recipe-maintainers:
    - alimanfoo
    - jakirkham
    - joshmoore
    - jrbourbeau
